name: syw
dependencies:
  - numpy
  - python=3.10
  - astropy
  - scipy
  - progress
  - matplotlib==3.4.3
  - Flask
  - pulp=2.8.0
  - nest-asyncio
  - snakemake
  - pip
  - pip:
      - git+https://github.com/thomasckng/showyourwork
