channels:
  - conda-forge
dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python=3.10
  - conda-forge::astropy
  - conda-forge::scipy
  - conda-forge::pulp=2.8.0
  - conda-forge::progress
  - pip:
      - matplotlib==3.4.3
