name: syw
dependencies:
  - conda-forge::numpy
  - conda-forge::python=3.10
  - conda-forge::astropy
  - conda-forge::scipy
  - conda-forge::progress
  - conda-forge::matplotlib==3.4.3
  - conda-forge::Flask
  - conda-forge::nest-asyncio
  - bioconda::snakemake
  - pip:
      - git+https://github.com/showyourwork/showyourwork
