name: syw
dependencies:
  - conda-forge::numpy
  - conda-forge::python=3.10
  - conda-forge::astropy
  - conda-forge::scipy
  - conda-forge::progress
  - conda-forge::matplotlib
  - conda-forge::Flask
  - conda-forge::pulp=2.8.0
  - conda-forge::nest-asyncio
  - bioconda::snakemake
  - conda-forge::pip
  - pip:
      - git+https://github.com/thomasckng/showyourwork
